version: "3.10"

services:

  guiadev:
    build:
      context: guiadev
      dockerfile: Dockerfile
    networks:
      - guiadev-network
    ports:
      - "8000:8000"
    restart: always

  guiadev-email:
    build:
      context: guiadev-email
      dockerfile: Dockerfile
    networks:
      - guiadev-network
    restart: always
    depends_on:
      - guiadev-rabbitmq

  guiadev-rabbitmq:
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    networks:
      - guiadev-network
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

networks:
  guiadev-network:
