# Generated by Django 4.2.1 on 2023-05-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=200)),
                ('total_contribuicoes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=10000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.autor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=10000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.autor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('resumo', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('total_likes', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.autor')),
                ('tecnologias', models.ManyToManyField(to='base.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialConteudo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField()),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.codigo')),
                ('marcacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.marcacao')),
                ('tutorial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.tutorial')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.autor')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tutorial')),
            ],
        ),
        migrations.AddField(
            model_name='codigo',
            name='linguagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tecnologia'),
        ),
    ]
