# Generated by Django 4.2.1 on 2023-05-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_tutorialconteudo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialconteudo',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tutorial'),
        ),
    ]
