# Generated by Django 4.2.1 on 2023-06-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_usuario',
            new_name='username',
        ),
    ]
