# Generated by Django 4.2 on 2023-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('guia_id', models.AutoField(primary_key=True, serialize=False)),
                ('guia_titulo', models.CharField(max_length=20)),
                ('guia_tecnologia', models.CharField(max_length=20)),
                ('guia_descricao', models.CharField(max_length=500)),
                ('guia_codigo', models.CharField(max_length=500)),
            ],
        ),
    ]
