# Generated by Django 4.2.1 on 2023-05-16 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='codigo',
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=10000)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=10000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.autor')),
                ('tutoriais', models.ManyToManyField(to='polls.tutorial')),
            ],
        ),
    ]
