# Generated by Django 4.2.1 on 2023-05-17 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_tutorial_codigo_marcacao_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicao', models.IntegerField(max_length=200)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.codigo')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tutorial')),
            ],
        ),
    ]
