# Generated by Django 4.2.1 on 2023-05-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='posicao',
            field=models.IntegerField(),
        ),
    ]
