# Generated by Django 4.2.1 on 2023-06-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['tutorial', 'usuario'], 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['tutorial', 'usuario'], 'verbose_name_plural': 'Likes'},
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tecnologias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tecnologia'),
        ),
    ]
